### ISSUE TITLE
Which wxWidgets version required?

### ISSUE THREAD

**Issue by vi** [madeso/ride#2]
Trying to build with wxwidgets-3.0.2:

    error: no matching function for call to ‘wxStyledTextCtrl::FindText(int&, int&, const wxString&, int&, int*&)’

Trying to build with wxWidgets 2.8.12.1-12:

    ride/ride/wxutils.h:35:30: error: ‘ButtonLabel’ in ‘class wxMessageDialogBase’ does not name a type

**Comment by madeso** [comment]
I'm using a forked wxwidgets 3 branch that can be found here: https://github.com/madeso/wxWidgets
and I'm working on getting it merged to the master via a pull request, though it needs some work: https://github.com/wxWidgets/wxWidgets/pull/23

If you don't want to use a special build, the travis build defines the cmake variables USE_WXWIDGETS_LEGACY_FINDTEXT and USE_CPP_AS_RUST

I've never tried to build it with 2x.
